### ISSUE TITLE
Multiple custom reporters

### ISSUE THREAD

**Issue by mjancarik** [theogravity/minijasminenode23#2]
Hi,

It could be good to set multipe custom reporters. It's possible?

**Comment by theogravity** [comment]
I have not tried 2.3 extensively, but it should given that 2.0 and 2.1 did.

**Comment by dflynn15** [comment]
The OP specifically was referencing a desire to have an "optional reporter" instead of an "additional reporter." What that means is that instead of using the default, you could substitute it for a custom reporter that would be run by default.

I put in a PR against minijasminenode here with all of the work against that repository.
https://github.com/juliemr/minijasminenode/pull/23

I have honestly not looked to see if it would be a simple replacement yet, but I can possibly submit in another PR against your repo seeing the lack of maintaining in https://github.com/juliemr/minijasminenode

**Comment by theogravity** [comment]
Ah gotcha. Yeah, don't mind if you want to try integrating it in.

**Comment by theogravity** [comment]
@dflynn15 I've added you as a repo collaborator and gave you publish rights to the npm module as well.

**Comment by dflynn15** [comment]
Hahaha thanks, I'll get you a PR today :+1:

**Comment by theogravity** [comment]
Published under `1.1.0`
